import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

/**
 *
 * @author Pedro Antonio
 */
public class Exportador extends javax.swing.JFrame {

    String nameFile;

    /**
     * Creates new form Exportador
     */
    public Exportador() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();
        lbWidth = new javax.swing.JLabel();
        lbHeigth = new javax.swing.JLabel();
        lbSize = new javax.swing.JLabel();
        btElegir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btElegir.setText("Elegir archivo");
        btElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSize)
                    .addComponent(lbHeigth)
                    .addComponent(lbWidth)
                    .addComponent(lbName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btElegir)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btElegir)
                .addGap(56, 56, 56)
                .addComponent(lbName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWidth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbHeigth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElegirActionPerformed
        final JFileChooser fc = new JFileChooser();
        int option = fc.showOpenDialog(this);
        nameFile = (fc.getSelectedFile().getPath());

        final int BUFFER_SIZE = 54;
        FileInputStream myFile = null;

        try {
            myFile = new FileInputStream(new File(nameFile));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        }
        byte[] buffer = new byte[BUFFER_SIZE];
        try {
            myFile.read(buffer, 0, BUFFER_SIZE);
        } catch (IOException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        }

        int heigth = 0;
        int width = 0;
        File file = new File(nameFile);
        double size = file.length();

        /*if(buffer[18] < 0){
            width = buffer[18] + 256; 
        }
        else{
            heigth = buffer[18];
        }
        heigth += (buffer[19] * 256);*/
        
        width = buffer[19] * 256 + buffer[18];
        if (buffer[18] < 0) {
             width += 256;
        }
        
        heigth = buffer[23] * 256 + buffer[22];
        if (buffer[22] < 0) {
            heigth += 256;
        }
        
        
        boolean isBMP = false;

        if ((buffer[0] == 'B') && (buffer[1] == 'M')) {
            isBMP = true;
        }

        if (isBMP) {
            lbName.setText(file.getName());
            lbWidth.setText("" + width + "");
            lbHeigth.setText("" + heigth + "");
            lbSize.setText("" + size + " kb");
        }
    }//GEN-LAST:event_btElegirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OutputStream outputStream;
        try {
            File file = new File("generatedXML.xml");
            outputStream = new FileOutputStream("generatedXML.xml", true);

            XMLStreamWriter out = XMLOutputFactory.newInstance().createXMLStreamWriter(
                    new OutputStreamWriter(outputStream, "utf-8"));

            if (file.exists()) {
                out.writeCharacters("\n");
                out.writeStartElement("ficheros");

                out.writeCharacters("\n");
                out.writeStartElement("fichero");

                out.writeCharacters("\n");
                out.writeStartElement("nombre");
                out.writeCharacters(lbName.getText());
                out.writeEndElement();
                out.writeCharacters("\n");
                out.writeStartElement("ancho");
                out.writeCharacters(lbWidth.getText());
                out.writeEndElement();
                out.writeCharacters("\n");
                out.writeStartElement("alto");
                out.writeCharacters(lbHeigth.getText());
                out.writeEndElement();
                out.writeCharacters("\n");
                out.writeStartElement("tamaño");
                out.writeCharacters(lbSize.getText());
                out.writeEndElement();
                out.writeCharacters("\n");
                out.writeEndElement();
                out.writeCharacters("\n");
                out.writeEndElement();

                out.writeEndDocument();
                out.flush();
            } else {
                out.writeStartDocument();
            }
            out.close();

            PrintWriter printwriter = new PrintWriter(new BufferedWriter(new FileWriter("generatedCSV.csv", true)));
            printwriter.append(/*"Nombre" +*/ lbName.getText()
                    + "," + lbWidth.getText() + "," + lbHeigth.getText() + ","
                    + lbSize.getText());
            printwriter.println();
            printwriter.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XMLStreamException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Exportador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exportador().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btElegir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbHeigth;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSize;
    private javax.swing.JLabel lbWidth;
    // End of variables declaration//GEN-END:variables
}
